import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import NavbarComponent from "@/components/navbar/NavbarComponent";
import { Suspense } from "react";
import Loading from "@/app/(user)/loading"
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "@/app/(user)/error"

//const inter = Inter({ subsets: ["latin"] });
import { inter,suwannaphum } from "./fonts";

export const metadata: Metadata = {
  title: "Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen flex flex-col ${inter.variable}`} >
        <header>
          <NavbarComponent/>
        </header>
        <ErrorBoundary errorComponent={
          Error}>
          <Suspense fallback={<Loading/>}>
            {children}
          </Suspense>
        </ErrorBoundary>
        
      </body>
    </html>
  );
}
